server:
  port: 8080
spring:
  application:
    name: "ScaffoldQuickStart"
  devtools:
    add-properties: false
  profiles:
    include: null
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5490/mydatabase}"
    username: "myuser"
    password: "mypassword"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "${SPRING_DATASOURCE_HOST:localhost}"
    port: "${SPRING_DATASOURCE_PORT:5490}"
    database: "${SPRING_DATASOURCE_DATABASE:mydatabase}"
    username: "${SPRING_DATASOURCE_USERNAME:myuser}"
    password: "${SPRING_DATASOURCE_PASSWORD:mypassword}"
